#!/bin/bash

cpu_gov="$1"
avail_govs="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)"
if [[ -z "$cpu_gov" ]]; then
    echo "available govenerors: $avail_govs"
    read -p "Please select a governor to use: " cpu_gov
fi

if [[ ! $avail_govs =~ (^| )$cpu_gov($| ) ]]; then
    echo "not a valid governor"
    exit 1
fi

echo "setting governor: $cpu_gov"

for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    sudo su -c "echo $cpu_gov > $i"
done
